### ISSUE TITLE
Mise à jour du fichier HTML

### ISSUE THREAD

**Issue by raphaelgoetter** [edenpulse/alstart#1]
Hey,

Je pense que le fichier HTML est issu de Schnapsit.
Mais il n'est plus vraiment à jour. Du coup je ne sais pas trop si mon commentaire est pertinent (il faudrait plutôt faire une mise à jour de Schnapsit)

- on pourrait presque virer tous les commentaires conditionnels pour IE puisqu'on ne bosse que pour du IE9IE10+
- on peut virer le HTML5shim

**Comment by edenpulse** [comment]
Hey, 
Totalement issu de Schnapsit oui, j'enlève les conditionnels IE.
Ca te parait bon comme ça ?
https://github.com/edenpulse/alstart/blob/master/index.html

**Comment by raphaelgoetter** [comment]
Oui globalement, mais : 

- tu as oublié la balise ouvrante `<html>`
- dans notre convention, `styles.min.css` est au pluriel
- pour les classes visuelles, il y aura sans doute du changement côté KNACSS v4, qui seront répercutés sur Schnapsit
