### ISSUE TITLE
Répertoire des dépendances

### ISSUE THREAD

**Issue by raphaelgoetter** [edenpulse/alstart#3]
Ton répertoire de dépendances, en tout cas pour KNACSS, semble être "vendor".
Pourtant, par défaut ce n'est pas celui qui sera choisi par Bower (ce sera bower_components).

Tu devrais peut-être créer un fichier `.bowerrc` pour indiquer clairement quel dossier sera celui des dépendances

**Comment by edenpulse** [comment]
Le .bowerrc existe déjà :) 

https://github.com/edenpulse/alstart/blob/master/.bowerrc
