### ISSUE TITLE
Autoprefixer ?

### ISSUE THREAD

**Issue by raphaelgoetter** [edenpulse/alstart#5]
Ce serait une bonne idée nan ?

https://www.npmjs.com/package/gulp-autoprefixer

**Comment by blupdew** [comment]
C'est à l'étude de mon côté :) On peut l'ajouter.
En a-t-on "encore" besoin sur les projets génériques ?

**Comment by raphaelgoetter** [comment]
oui

**Comment by edenpulse** [comment]
Autoprefixer pour Gulp à été rajouté

**Comment by raphaelgoetter** [comment]
#beaugosse

**Comment by edenpulse** [comment]
<3 #coeuraveclesdoigts
