### ISSUE TITLE
Gulp / grunt ?

### ISSUE THREAD

**Issue by edenpulse** [edenpulse/alstart#7]
Sur lequel met-on l'accent ? 
Gulp semble remporter les suffrages, qu'en pensez vous @blupdew @raphaelgoetter ?
Est-ce que ça vaut le coup de maintenir les 2 scripts ?

**Comment by raphaelgoetter** [comment]
Je pense que Gulp suffit.

**Comment by blupdew** [comment]
Gulp+1, OK pour un seul script pour ne pas disperser l'énergie.
Si vraiment il faut un jour passer sur grunt ou un équivalent ce sera toujours possible : le principe est toujours le même.

**Comment by edenpulse** [comment]
Ok, validay, lors de la prochaine version je vire tout ce qui à attrait à Grunt
